services:
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - app_node_modules:/app/node_modules  # Changed to named volume
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host

volumes:
  app_node_modules:  # Added this section
